### ISSUE TITLE
Cannot generate test results attributes when using gradle

### ISSUE THREAD

**Issue by barranquerox** [bitcoder/xray-testng-extensions#7]
Is there a way to enable generateTestResultAttributes to "true" as explained [here](https://docs.getxray.app/display/XRAYCLOUD/Testing+using+TestNG+in+Java) but using gradle?

**Comment by bitcoder** [comment]
Sorry, I missed your question; it's a good one. I'm not sure; I'm still learning gradle. I remember that I tried this some time ago but without success, I think.

**Comment by bitcoder** [comment]
I confirm that I wasn't able to get it work back then.. need to revisit this topic

**Comment by bitcoder** [comment]
Create a new task (e.g. "testngTest") and then run it using `gradle testngTest`


```
task testngTest(type: JavaExec, dependsOn: [classes]) {
    group 'Verification'
    description 'Run'
    mainClass = 'org.testng.TestNG'
    args('testng.xml', '-reporter',
            'org.testng.reporters.XMLReporter:generateTestResultAttributes=true,generateGroupsAttribute=true'
    )
    classpath = sourceSets.test.runtimeClasspath
}
```

This seems to work fine
